"""Step 22.5 (PAPER_TRADING_V1.4.4): the durable, immutable record of one
new-position candidate the daily unattended validation cycle surfaced for
human review, plus the append-only audit trail of every confirmation
attempt against it.

`ReviewedCandidate` is created exactly once, by `scripts/run_validation_cycle
.py`, with `status=AWAITING_HUMAN` -- nothing in this module or
`src.review.confirmation` may ever change the ECONOMIC fields of an
existing candidate (`proposal`, `quantitative_analysis`, `risk_decision`,
etc.); only `status`/`resolved_at`/`resolution_reason`/`paper_order_id`/
`paper_client_order_id` are ever updated, via a full-record REPLACE that
always carries the original economic fields forward unchanged. This is the
concrete mechanism behind "confirmation is authorization, not trade
selection" -- there is no code path anywhere that edits a candidate's
strategy, strikes, expiration, quantity, or sizing after creation; a
candidate whose terms need to change is rejected/expired and a new one is
generated by the next daily cycle.
"""
from __future__ import annotations

import json
import sqlite3
import statistics
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from pathlib import Path

from src.llm.schemas import TradeProposal
from src.risk.engine import RiskDecisionResult
from src.risk.trade_risk import QuantitativeAnalysis
from src.validation.records import from_jsonable, to_jsonable


class CandidateStatus(str, Enum):
    AWAITING_HUMAN = "awaiting_human"
    CONFIRMED = "confirmed"
    REJECTED = "rejected"
    EXPIRED = "expired"
    REPRICE_REQUIRED = "reprice_required"
    DATA_INSUFFICIENT = "data_insufficient"
    # Mirrors src.orchestration.pipeline.PipelineStatus.NO_FILL's own
    # value/meaning exactly -- an accepted order that simply didn't fill
    # (e.g. thin liquidity), never a rejection.
    NO_FILL = "no_fill"


_TERMINAL_STATUSES = frozenset(
    {
        CandidateStatus.CONFIRMED, CandidateStatus.REJECTED, CandidateStatus.EXPIRED,
        CandidateStatus.REPRICE_REQUIRED, CandidateStatus.DATA_INSUFFICIENT, CandidateStatus.NO_FILL,
    }
)


@dataclass(frozen=True)
class ReviewedCandidate:
    """The full immutable review snapshot -- every economically relevant
    field a human (or a future automated authorization policy, per this
    step's own "future automation" design goal) needs to authorize this
    exact candidate, and nothing that could let confirmation alter it."""

    candidate_id: str  # == TradeProposal.proposal_id == the eventual PlaceOrderRequest.client_order_id
    cohort_id: str
    cycle_id: str
    created_at: datetime
    ttl_seconds: int
    proposal: TradeProposal
    quantitative_analysis: QuantitativeAnalysis
    risk_decision: RiskDecisionResult
    entry_delta: float
    entry_iv: float | None
    quote_timestamp: datetime
    market_data_source: str
    portfolio_exposure_before_pct: float
    portfolio_exposure_after_pct: float
    sector_exposure_before_pct: float
    sector_exposure_after_pct: float
    management_policy_name: str
    # Always False for every candidate this cohort produces -- no LLM
    # review of any kind occurs in this Review-Only execution model (see
    # src.review.confirmation's module docstring). Recorded explicitly so
    # no downstream report can imply full multi-agent qualitative review
    # happened.
    llm_review_performed: bool = False
    status: CandidateStatus = CandidateStatus.AWAITING_HUMAN
    resolved_at: datetime | None = None
    resolution_reason: str | None = None
    paper_order_id: str | None = None
    paper_client_order_id: str | None = None

    @property
    def is_terminal(self) -> bool:
        return self.status in _TERMINAL_STATUSES

    @property
    def expires_at(self) -> datetime:
        return self.created_at + timedelta(seconds=self.ttl_seconds)

    def is_expired(self, as_of: datetime) -> bool:
        return as_of >= self.expires_at


@dataclass(frozen=True)
class ConfirmationAttemptRecord:
    """One append-only audit row per `confirm_candidate` invocation
    against a given candidate -- never rewritten, so a second attempt
    (successful or not) never erases evidence of the first. No subjective
    human rationale is recorded anywhere here or on `ReviewedCandidate` --
    only the mechanical revalidation result, per this step's own explicit
    "operational safety and authorization, not discretionary trade
    selection" purpose."""

    attempt_id: str
    candidate_id: str
    attempted_at: datetime
    outcome: str  # a ConfirmationOutcome.value (src.review.confirmation)
    detail: str
    original_quoted_economics: dict
    refreshed_economics: dict | None = None
    paperbroker_result: dict | None = None


class CandidateReviewStore(ABC):
    @abstractmethod
    def save_candidate(self, candidate: ReviewedCandidate) -> None: ...

    @abstractmethod
    def get_candidate(self, candidate_id: str) -> ReviewedCandidate | None: ...

    @abstractmethod
    def candidates_awaiting_human(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]: ...

    @abstractmethod
    def candidates_for_cycle(self, cycle_id: str) -> list[ReviewedCandidate]: ...

    @abstractmethod
    def all_candidates(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]: ...

    @abstractmethod
    def record_confirmation_attempt(self, attempt: ConfirmationAttemptRecord) -> None: ...

    @abstractmethod
    def confirmation_attempts_for_candidate(self, candidate_id: str) -> list[ConfirmationAttemptRecord]: ...


class InMemoryCandidateReviewStore(CandidateReviewStore):
    """Process-local only -- lost on restart. For tests and any caller
    that doesn't need restart-survival."""

    def __init__(self) -> None:
        self._candidates: dict[str, ReviewedCandidate] = {}
        self._attempts: list[ConfirmationAttemptRecord] = []

    def save_candidate(self, candidate: ReviewedCandidate) -> None:
        self._candidates[candidate.candidate_id] = candidate

    def get_candidate(self, candidate_id: str) -> ReviewedCandidate | None:
        return self._candidates.get(candidate_id)

    def candidates_awaiting_human(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]:
        values = [c for c in self._candidates.values() if c.status == CandidateStatus.AWAITING_HUMAN]
        if cohort_id is not None:
            values = [c for c in values if c.cohort_id == cohort_id]
        return values

    def candidates_for_cycle(self, cycle_id: str) -> list[ReviewedCandidate]:
        return [c for c in self._candidates.values() if c.cycle_id == cycle_id]

    def all_candidates(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]:
        values = list(self._candidates.values())
        if cohort_id is not None:
            values = [c for c in values if c.cohort_id == cohort_id]
        return values

    def record_confirmation_attempt(self, attempt: ConfirmationAttemptRecord) -> None:
        self._attempts.append(attempt)

    def confirmation_attempts_for_candidate(self, candidate_id: str) -> list[ConfirmationAttemptRecord]:
        return [a for a in self._attempts if a.candidate_id == candidate_id]


class SqliteCandidateReviewStore(CandidateReviewStore):
    """A durable `CandidateReviewStore` backed by a single sqlite file.
    Each operation opens and closes its own connection, the same pattern
    every other Sqlite store in this codebase already uses."""

    def __init__(self, db_path: Path | str) -> None:
        self._path = str(db_path)
        Path(self._path).parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as conn:
            conn.execute(
                "CREATE TABLE IF NOT EXISTS reviewed_candidates ("
                "candidate_id TEXT PRIMARY KEY, cohort_id TEXT NOT NULL, cycle_id TEXT NOT NULL, "
                "status TEXT NOT NULL, candidate_json TEXT NOT NULL)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_reviewed_candidates_cohort ON reviewed_candidates(cohort_id)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_reviewed_candidates_cycle ON reviewed_candidates(cycle_id)"
            )
            conn.execute(
                "CREATE TABLE IF NOT EXISTS confirmation_attempts ("
                "row_id INTEGER PRIMARY KEY AUTOINCREMENT, candidate_id TEXT NOT NULL, attempt_json TEXT NOT NULL)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_confirmation_attempts_candidate ON confirmation_attempts(candidate_id)"
            )

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self._path)

    def save_candidate(self, candidate: ReviewedCandidate) -> None:
        candidate_json = _dump(candidate, ReviewedCandidate)
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO reviewed_candidates (candidate_id, cohort_id, cycle_id, status, candidate_json) "
                "VALUES (?, ?, ?, ?, ?) ON CONFLICT(candidate_id) DO UPDATE SET "
                "cohort_id=excluded.cohort_id, cycle_id=excluded.cycle_id, "
                "status=excluded.status, candidate_json=excluded.candidate_json",
                (candidate.candidate_id, candidate.cohort_id, candidate.cycle_id, candidate.status.value, candidate_json),
            )

    def get_candidate(self, candidate_id: str) -> ReviewedCandidate | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT candidate_json FROM reviewed_candidates WHERE candidate_id = ?", (candidate_id,)
            ).fetchone()
        return _load(row[0], ReviewedCandidate) if row is not None else None

    def candidates_awaiting_human(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]:
        query = "SELECT candidate_json FROM reviewed_candidates WHERE status = ?"
        params: tuple = (CandidateStatus.AWAITING_HUMAN.value,)
        if cohort_id is not None:
            query += " AND cohort_id = ?"
            params += (cohort_id,)
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [_load(r[0], ReviewedCandidate) for r in rows]

    def candidates_for_cycle(self, cycle_id: str) -> list[ReviewedCandidate]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT candidate_json FROM reviewed_candidates WHERE cycle_id = ?", (cycle_id,)
            ).fetchall()
        return [_load(r[0], ReviewedCandidate) for r in rows]

    def all_candidates(self, *, cohort_id: str | None = None) -> list[ReviewedCandidate]:
        query = "SELECT candidate_json FROM reviewed_candidates"
        params: tuple = ()
        if cohort_id is not None:
            query += " WHERE cohort_id = ?"
            params = (cohort_id,)
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
        return [_load(r[0], ReviewedCandidate) for r in rows]

    def record_confirmation_attempt(self, attempt: ConfirmationAttemptRecord) -> None:
        attempt_json = _dump(attempt, ConfirmationAttemptRecord)
        with self._connect() as conn:
            conn.execute(
                "INSERT INTO confirmation_attempts (candidate_id, attempt_json) VALUES (?, ?)",
                (attempt.candidate_id, attempt_json),
            )

    def confirmation_attempts_for_candidate(self, candidate_id: str) -> list[ConfirmationAttemptRecord]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT attempt_json FROM confirmation_attempts WHERE candidate_id = ? ORDER BY row_id",
                (candidate_id,),
            ).fetchall()
        return [_load(r[0], ConfirmationAttemptRecord) for r in rows]


def _dump(value, type_) -> str:
    return json.dumps(to_jsonable(value, type_))


def _load(raw: str, type_):
    return from_jsonable(json.loads(raw), type_)


@dataclass(frozen=True)
class CandidateReviewFunnelCounts:
    """Human-confirmation behavior, tracked separately from strategy
    performance -- per this step's own explicit instruction that
    confirmation behavior must never be hidden inside performance
    numbers."""

    cohort_id: str
    presented: int
    confirmed: int
    rejected: int
    expired: int
    reprice_required: int
    data_insufficient: int
    no_fill: int
    median_seconds_to_resolution: float | None
    mean_seconds_to_resolution: float | None


def funnel_counts(store: CandidateReviewStore, *, cohort_id: str) -> CandidateReviewFunnelCounts:
    candidates = store.all_candidates(cohort_id=cohort_id)
    by_status = {status: 0 for status in CandidateStatus}
    resolution_seconds: list[float] = []
    for c in candidates:
        by_status[c.status] += 1
        if c.resolved_at is not None:
            resolution_seconds.append((c.resolved_at - c.created_at).total_seconds())

    return CandidateReviewFunnelCounts(
        cohort_id=cohort_id,
        presented=len(candidates),
        confirmed=by_status[CandidateStatus.CONFIRMED],
        rejected=by_status[CandidateStatus.REJECTED],
        expired=by_status[CandidateStatus.EXPIRED],
        reprice_required=by_status[CandidateStatus.REPRICE_REQUIRED],
        data_insufficient=by_status[CandidateStatus.DATA_INSUFFICIENT],
        no_fill=by_status[CandidateStatus.NO_FILL],
        median_seconds_to_resolution=statistics.median(resolution_seconds) if resolution_seconds else None,
        mean_seconds_to_resolution=statistics.fmean(resolution_seconds) if resolution_seconds else None,
    )
