"""Part 17: the immutable `LifecycleDecisionSnapshot`.

Generated by every single lifecycle evaluation (`src.lifecycle.engine`)
and persisted (`src.lifecycle.persistence`, Part 237) so the full
history of a position lets anyone reconstruct exactly WHY it was held
or closed, after the fact, without re-deriving it from raw market data
that may no longer even be available. Never mutated after creation —
the engine builds a fresh one on every evaluation, it never edits a
previous one.
"""
from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, field_validator

from src.lifecycle.precedence import ResolvedAction
from src.lifecycle.state import PositionLifecycleState
from src.lifecycle.triggers import TriggerFinding
from src.strategies.base import StrategyKind


def _tz_aware(v: datetime) -> datetime:
    if v.tzinfo is None:
        raise ValueError("timestamp fields must be timezone-aware")
    return v


class TriggerFindingRecord(BaseModel):
    """A persisted, serializable copy of one `TriggerFinding` — the
    dataclass in `src.lifecycle.triggers` is deliberately not a Pydantic
    model (it's pure in-memory evaluation plumbing), so the snapshot
    keeps its own strict, `extra="forbid"` record shape for storage."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    trigger_name: str
    category: str
    target_state: PositionLifecycleState
    mandatory: bool
    reason: str

    @classmethod
    def from_finding(cls, finding: TriggerFinding) -> "TriggerFindingRecord":
        return cls(
            trigger_name=finding.trigger_name,
            category=finding.category,
            target_state=finding.target_state,
            mandatory=finding.mandatory,
            reason=finding.reason,
        )


class LifecycleDecisionSnapshot(BaseModel):
    """One immutable record of a single lifecycle evaluation — Part
    17's exact field list. `management_policy` is recorded as the
    policy's own `name` (its unique research-label identity,
    `src.lifecycle.policy.ManagementPolicy.name`) rather than the full
    object, keeping the snapshot a flat, cheaply-persisted record; the
    full policy definition is looked up by name from
    `src.lifecycle.policies_library`, itself frozen once validation
    begins (Part 26)."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    trade_id: str
    wheel_id: str | None = None
    timestamp: datetime
    strategy: StrategyKind
    management_policy: str
    current_state: PositionLifecycleState

    underlying_price: float | None = None
    option_prices: dict[str, float] = {}
    delta: float | None = None
    gamma: float | None = None
    theta: float | None = None
    vega: float | None = None
    iv: float | None = None
    dte: int | None = None

    mfe: float
    mae: float
    unrealized_pnl: float
    realized_pnl: float

    portfolio_exposure_pct: float | None = None
    drawdown_pct: float | None = None
    market_regime: str | None = None

    candidate_actions: tuple[TriggerFindingRecord, ...] = ()
    deterministic_action_category: str
    deterministic_action_target_state: PositionLifecycleState
    deterministic_action_mandatory: bool
    deterministic_action_reason: str

    risk_status: str
    data_is_fresh: bool
    reason_codes: tuple[str, ...] = ()

    _validate_tz = field_validator("timestamp")(_tz_aware)


def build_snapshot(
    *,
    trade_id: str,
    wheel_id: str | None,
    timestamp: datetime,
    strategy: StrategyKind,
    management_policy_name: str,
    current_state: PositionLifecycleState,
    underlying_price: float | None,
    option_prices: dict[str, float] | None = None,
    delta: float | None = None,
    gamma: float | None = None,
    theta: float | None = None,
    vega: float | None = None,
    iv: float | None = None,
    dte: int | None = None,
    mfe: float,
    mae: float,
    unrealized_pnl: float,
    realized_pnl: float,
    portfolio_exposure_pct: float | None = None,
    drawdown_pct: float | None = None,
    market_regime: str | None = None,
    findings: list[TriggerFinding],
    resolved: ResolvedAction,
    risk_status: str,
    data_is_fresh: bool,
) -> LifecycleDecisionSnapshot:
    return LifecycleDecisionSnapshot(
        trade_id=trade_id,
        wheel_id=wheel_id,
        timestamp=timestamp,
        strategy=strategy,
        management_policy=management_policy_name,
        current_state=current_state,
        underlying_price=underlying_price,
        option_prices=option_prices or {},
        delta=delta,
        gamma=gamma,
        theta=theta,
        vega=vega,
        iv=iv,
        dte=dte,
        mfe=mfe,
        mae=mae,
        unrealized_pnl=unrealized_pnl,
        realized_pnl=realized_pnl,
        portfolio_exposure_pct=portfolio_exposure_pct,
        drawdown_pct=drawdown_pct,
        market_regime=market_regime,
        candidate_actions=tuple(TriggerFindingRecord.from_finding(f) for f in findings),
        deterministic_action_category=resolved.category,
        deterministic_action_target_state=resolved.target_state,
        deterministic_action_mandatory=resolved.mandatory,
        deterministic_action_reason=resolved.reason,
        risk_status=risk_status,
        data_is_fresh=data_is_fresh,
        reason_codes=tuple(f.trigger_name for f in findings),
    )
